INSERT IGNORE INTO email_list (`id`,`name`,`system_lock`) VALUES (2,'Newsletter',1);



INSERT IGNORE INTO email (`id`,`name`,`account`,`sender`,`subject`,`template_text`,`template_html`,`system_lock`) VALUES (10,'Website Contact','test@webcraft-media.de','${data_vorname} ${data_nachname} <${data_email}>','${emoji_mobile} DEMOCRACY Website: ${data_type} from ${data_email}',10,11,1);
INSERT IGNORE INTO email_template (`id`,`type`,`name`,`value`,`system_lock`) VALUES (10,0,'Website Contact Text','Eine Nachricht ist über die Website eingegangen:\n\n${data_json}\n\nAchtung: Diese EMail ist die einzige Kopie dieser Daten',1);
INSERT IGNORE INTO email_template (`id`,`type`,`name`,`value`,`system_lock`) VALUES (11,1,'Website Contact HTML','<style>\n    table, th, td {\n        border: 1px solid black;\n        border-collapse: collapse;\n    }\n</style>\nEine Nachricht ist über die Website eingegangen:<br>\n<br>\n<h3>Type: ${data_type}</h3>\n<table>\n    <tr>\n        <th>EMail</th>\n        <td><a href=\"mailto:${data_email}\">${data_email}<a></td>\n    </tr>\n    <tr>\n        <th>Name</th>\n        <td>${data_vorname} ${data_nachname}</td>\n    </tr>\n    <tr>\n        <th>Type</th>\n        <td>${data_type}</td>\n    </tr>\n    <tr>\n        <th>Text</th>\n        <td><pre>${data_text}</pre></td>\n    </tr>\n</table>\n<h3>Raw Data:</h3>\n<pre>${data_json}</pre>\n<br>\n<div class=\"footer\" style=\"margin-top: 3em; padding-top: 1em; border-top-width: 2px; border-top-color: #4494d3; border-top-style: solid;\">\n    <p style=\"max-width: 35rem;\">\n        Wir sind gespannt, welche großartigen Möglichkeiten in der Zukunft noch für unser Projekt offen stehen und verbleiben mit einem Lächeln und ganz herzlichen Grüßen,\n    </p>  \n    <p style=\"max-width: 35rem;\">\n        Ihr TEAM DEMOCRACY\n    </p>\n    <img class=\"logo\" alt=\"DEMOCRACY Logo\" src=\"cid:democracy_logo\" style=\"height: auto; line-height: 100%; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; border: 0 none;\" />\n    <p style=\"max-width: 35rem;\">\n      DEMOCRACY Deutschland e.V.<br />\n      mobil +49 176 470 40 213<br />\n      <a href=\"mailto:contact@democracy-deutschland.de\" style=\"color: #4f81bd; font-weight: bold;\">\n        contact@democracy-deutschland.de\n      </a><br />\n      <a href=\"https://www.democracy-deutschland.de\" style=\"color: #4f81bd; font-weight: bold;\">\n          https://www.democracy-deutschland.de\n      </a><br />\n      <a href=\"https://github.com/demokratie-live/\" style=\"color: #4f81bd; font-weight: bold;\">\n          https://github.com/demokratie-live\n      </a>\n    </p>\n  </div>\n',1);

INSERT IGNORE INTO email (`id`,`name`,`account`,`sender`,`subject`,`template_text`,`template_html`,`system_lock`) VALUES (20,'Newsletter Subscribe','test@webcraft-media.de','DEMOCRACY Deutschland e.V. <contact@democracy-deutschland.de>','${emoji_mobile} DEMOCRACY: Deine Newsletter-Anmeldung',20,21,1);
INSERT IGNORE INTO email_template (`id`,`type`,`name`,`value`,`system_lock`) VALUES (20,0,'Newsletter Subscribe Text','Hallo liebe/r Interessierte/r,\n\nSie haben sich für unseren Newsletter eingetragen.\n\nUm sich wieder abzumelden folgen Sie bitte folgendem Link:\n${unsubscribe_link}\n\nHerzliche Grüße\nTeam DEMOCRACY',1);
INSERT IGNORE INTO email_template (`id`,`type`,`name`,`value`,`system_lock`) VALUES (21,1,'Newsletter Subscribe HTML','Hallo liebe/r Interessierte/r,<br>\n<br>\nSie haben sich für unseren Newsletter eingetragen.<br>\n<br>\nUm sich wieder abzumelden folgen Sie bitte diesem <a href=\"${unsubscribe_link}\">Abmelde-Link</a><br>\n<br>\nHerzliche Grüße<br>\nTeam DEMOCRACY',1);